#!/bin/bash

echo " current at :"
pwd
echo " the first and the second are for the dir"
echo " the third for the seed"
echo " run as: filename  dir1  dir2 seed"

home=`pwd`

cd $1

pwd

rm diff1.out

make testdominion


./testdominion $3 >> diff1.out

gcov -f -b dominion.c 

cd $2

pwd

rm diff2.out

make testdominion	

./testdominion $3 >> diff2.out

mv diff2.out $1

gcov -f -b dominion.c 

pwd

cd ..

diff diff1.out diff2.out > diff3.out
if [ ! -s diff3.out ]	
	then
		echo "TEST PASSED"
	else
		echo "TEST FAILED"
fi
